# Generated by Django 5.2.16 on 2026-07-29 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.TextField()),
                ('memo_date', models.DateField()),
                ('body', models.TextField()),
                ('via_voice', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm_memo',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.TextField()),
                ('media_type', models.CharField(choices=[('image', '사진'), ('video', '동영상')], max_length=10)),
                ('size_bytes', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='journal.farmmemo')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_kind', models.CharField(choices=[('command', '음성 명령'), ('memo', '음성 메모')], max_length=10)),
                ('spoken_text', models.TextField(blank=True, null=True)),
                ('recognized_intent', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('executed', '실행됨'), ('rejected', '거부됨'), ('fallback', '텍스트 폴백')], max_length=10, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voice_log',
            },
        ),
        migrations.AddIndex(
            model_name='farmmemo',
            index=models.Index(fields=['farm_id', 'memo_date'], name='farm_memo_farm_id_348f67_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('media_type__in', ['image', 'video'])), name='attachment_media_type_check'),
        ),
        migrations.AddIndex(
            model_name='voicelog',
            index=models.Index(fields=['user', 'occurred_at'], name='voice_log_user_id_5f3d7e_idx'),
        ),
    ]
