from django.urls import path

from apps.accounts import views as auth_views
from apps.journal import views as journal_views
from apps.core.views import (
    all_alerts,
    environment_history,
    environment_summary,
    alert_ack,
    alert_rule_update,
    alert_rules,
    alerts_ack_all,
    device_control,
    discovery,
    discovery_register,
    farm_alerts,
    farm_commands,
    farm_layout,
    farm_detail,
    farm_device_detail,
    farm_devices,
    farm_snapshot,
    farm_stop_state,
    farms,
    health,
    stop_engage,
    reverse_region,
    stop_release,
    stop_state_all,
    weather,
)

urlpatterns = [
    path("health", health),
    path("api/health", health),  # nginx 단일 진입점(/api → api) 경유용
    path("api/auth/login", auth_views.login),
    path("api/auth/logout", auth_views.logout),
    path("api/auth/refresh", auth_views.refresh),
    path("api/auth/me", auth_views.me),
    path("api/farms", farms),
    path("api/weather", weather),
    path("api/discovery", discovery),
    path("api/discovery/<str:farm_id>/register", discovery_register),
    path("api/farms/<str:farm_id>", farm_detail),
    path("api/regions/reverse", reverse_region),
    path("api/farms/<str:farm_id>/devices", farm_devices),
    path("api/farms/<str:farm_id>/devices/<str:device_id>", farm_device_detail),
    path("api/farms/<str:farm_id>/snapshot", farm_snapshot),
    path("api/farms/<str:farm_id>/commands", farm_commands),
    path("api/farms/<str:farm_id>/layout", farm_layout),
    path("api/farms/<str:farm_id>/devices/<str:device_id>/control", device_control),
    path("api/alerts", all_alerts),
    path("api/farms/<str:farm_id>/environment/history", environment_history),
    path("api/farms/<str:farm_id>/environment/summary", environment_summary),
    path("api/memos", journal_views.memos),
    path("api/memos/<int:memo_id>", journal_views.memo_detail),
    path("api/farms/<str:farm_id>/alerts", farm_alerts),
    path("api/farms/<str:farm_id>/alerts/ack-all", alerts_ack_all),
    path("api/alerts/<int:alert_id>/ack", alert_ack),
    path("api/farms/<str:farm_id>/alert-rules", alert_rules),
    path("api/alert-rules/<int:rule_id>", alert_rule_update),
    path("api/farms/<str:farm_id>/stop-state", farm_stop_state),
    path("api/stop-state", stop_state_all),
    path("api/stop", stop_engage),
    path("api/stop/release", stop_release),
]
