from django.urls import path

from apps.accounts import views as auth_views
from apps.journal import views as journal_views
from apps.core.views import (
    all_alerts,
    environment_history,
    environment_summary,
    alert_ack,
    alert_rule_update,
    alert_rules,
    alert_rules_bulk,
    alerts_ack_all,
    device_control,
    discovery,
    discovery_register,
    resolve_farm_address,
    resolve_farm_location,
    search_farm_addresses,
    farm_alerts,
    farm_commands,
    farm_layout,
    farm_detail,
    farm_device_detail,
    farm_devices,
    farm_snapshots,
    farm_stop_state,
    farms,
    health,
    robot_jog,
    stop_engage,
    stop_release,
    stop_state_all,
    weather,
    weather_refresh,
)

urlpatterns = [
    path("health", health),
    path("api/health", health),  # nginx 단일 진입점(/api → api) 경유용
    path("api/auth/login", auth_views.login),
    path("api/auth/logout", auth_views.logout),
    path("api/auth/refresh", auth_views.refresh),
    path("api/auth/me", auth_views.me),
    path("api/farms", farms),
    path("api/weather", weather),
    path("api/farms/<str:farm_id>/weather/refresh", weather_refresh),
    path("api/discovery", discovery),
    path("api/discovery/<str:farm_id>/register", discovery_register),
    path("api/location/resolve-current", resolve_farm_location),
    path("api/location/resolve-address", resolve_farm_address),
    path("api/location/search-addresses", search_farm_addresses),
    # <farm_id> 패턴보다 앞 — 뒤에 두면 "snapshots" 가 farm_id 로 잡힌다
    path("api/farms/snapshots", farm_snapshots),
    path("api/farms/<str:farm_id>", farm_detail),
    path("api/farms/<str:farm_id>/devices", farm_devices),
    path("api/farms/<str:farm_id>/devices/<str:device_id>", farm_device_detail),
    path("api/farms/<str:farm_id>/commands", farm_commands),
    path("api/farms/<str:farm_id>/layout", farm_layout),
    path("api/farms/<str:farm_id>/devices/<str:device_id>/control", device_control),
    path("api/farms/<str:farm_id>/robots/<str:device_id>/jog", robot_jog),
    path("api/alerts", all_alerts),
    path("api/farms/<str:farm_id>/environment/history", environment_history),
    path("api/farms/<str:farm_id>/environment/summary", environment_summary),
    path("api/memos", journal_views.memos),
    path("api/memos/with-attachments", journal_views.memo_with_attachments),
    path("api/memos/attachments/<int:attachment_id>", journal_views.memo_attachment),
    path("api/memos/<int:memo_id>/attachments", journal_views.memo_update_with_attachments),
    path("api/memos/<int:memo_id>", journal_views.memo_detail),
    path("api/farms/<str:farm_id>/alerts", farm_alerts),
    path("api/farms/<str:farm_id>/alerts/ack-all", alerts_ack_all),
    path("api/alerts/<int:alert_id>/ack", alert_ack),
    path("api/farms/<str:farm_id>/alert-rules", alert_rules),
    path("api/alert-rules", alert_rules_bulk),
    path("api/alert-rules/<int:rule_id>", alert_rule_update),
    path("api/farms/<str:farm_id>/stop-state", farm_stop_state),
    path("api/stop-state", stop_state_all),
    path("api/stop", stop_engage),
    path("api/stop/release", stop_release),
]
